"""Generate keytable.h from layout.py, so the emulator and the skin agree on group/bit."""
import os, sys
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from layout import KEYS, ARROWS

def alpha_of(rest):
    # KEYS rows are (cx, cy, class, legend, 2nd, alpha)
    a = rest[5] if len(rest) > 5 else None
    if not a or len(a) != 1 or a not in 'ABCDEFGHIJKLMNOPQRSTUVWXYZ':
        return ''
    return a
rows = [(n, g, b, alpha_of(rest)) for n, g, b, *rest in KEYS] + [(n, g, b, '') for n, g, b, _ in ARROWS]
out = ['/* generated by gen_keytable.py from ../layout.py - do not edit */',
       '#ifndef KEYTABLE_H', '#define KEYTABLE_H',
       'typedef struct { const char *name; int group, bit; char alpha; } tikey_t;',
       'static const tikey_t TIKEYS[] = {']
for n, g, b, a in rows:
    out.append('    { "%s", %d, %d, \'%s\' },' % (n.replace('\\', '\\\\').replace('"', '\\"'), g, b, a or '\\0'))
out += ['};', '#define TIKEY_COUNT ((int)(sizeof(TIKEYS) / sizeof(TIKEYS[0])))', '#endif', '']
open(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'keytable.h'), 'w').write('\n'.join(out))
print('wrote keytable.h with', len(rows), 'keys')
